using FishingMartPos.Domain;
using Xunit;

namespace FishingMartPos.Tests.Domain;

public class BarcodeGeneratorTests
{
    [Fact]
    public void GenerateNext_WithNoExistingBarcodes_StartsAt70000()
    {
        var result = BarcodeGenerator.GenerateNext(Array.Empty<string>());

        Assert.Equal("70000", result);
    }

    [Fact]
    public void GenerateNext_WithExistingAutoGeneratedBarcodes_ReturnsMaxPlusOne()
    {
        var existing = new[] { "70000", "70050", "70003" };

        var result = BarcodeGenerator.GenerateNext(existing);

        Assert.Equal("70051", result);
    }

    [Fact]
    public void GenerateNext_IgnoresBarcodesOutsideTheAutoGeneratedRange()
    {
        // 기존 수동 등록 바코드들(미끼/생활용품/금액 상품 등)은 70000~99999 구간 밖이라
        // 자동 생성 번호 계산에 영향을 주면 안 된다.
        var existing = new[] { "10001", "50001", "100000", "8800000020099", "9999999999999" };

        var result = BarcodeGenerator.GenerateNext(existing);

        Assert.Equal("70000", result);
    }

    [Fact]
    public void GenerateNext_WhenCandidateAlreadyUsedByManualEntry_SkipsToNextFreeNumber()
    {
        // 과거에 70000번대 숫자가 수동으로 이미 쓰였더라도 절대 중복 바코드를 만들지 않는다.
        var existing = new[] { "70000", "70001" };

        var result = BarcodeGenerator.GenerateNext(existing);

        Assert.Equal("70002", result);
    }
}
